name: Push
on: [push]

jobs:
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.10']
        poetry-version: ['1.4.2']
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.1.4
        with:
          poetry-version: ${{ matrix.poetry-version }}
      - name: Check directory contents
        run: ls -la services/talk_booking
      - name: Install dependencies
        run: cd services/talk_booking && poetry install
      - name: Run black
        run: cd services/talk_booking && poetry run black . --check -v

      - name: Run isort
        run: cd services/talk_booking && poetry run isort . --check-only --profile black -v

      - name: Run flake8
        run: cd services/talk_booking && poetry run flake8 . -v

      - name: Run bandit
        run: cd services/talk_booking && poetry run bandit . -v

